export const API = process.env.REACT_APP_API_URL;
export const EMAIL_JS_SERVICE_ID = process.env.REACT_APP_API_EMAIL_JS_SERVICE_ID;
export const EMAIL_JS_TEMPLATE_ID = process.env.REACT_APP_API_EMAIL_JS_TEMPLATE_ID;
export const EMAIL_JS_PUBLIC_API_KEY = process.env.REACT_APP_API_EMAIL_JS_PUBLIC_API_KEY;